
###
# Development environment configuration
##

# Application settings
APP_NAME: '${pkg.name}'
APP_VERSION: '${pkg.version}'
APP_BASE_URL: 'http://localhost:8080'

# API settings
API_VERSION: 1
API_BASE_URL: 'http://localhost:8081'

# Server settings
SERVER_PORT: 8081

# Database settings
DB_URI: 'mongodb://localhost/my-application'
DB_DEBUG: true
DB_USER: ''
DB_PASS: ''

# Authentication settings
REFRESH_TOKEN_HTTPS_ONLY: false
REFRESH_TOKEN_MAX_AGE: 30 * 24 * 3600
